In [2]:
print('Hello world')

Hello world


In [3]:
lista = [1, 2, 3, 4, 5]

In [5]:
!pipenv install numpy

Installing numpy...
Adding numpy to Pipfile's [packages]...
✔ Installation Succeeded 
Installing dependencies from Pipfile.lock (be70db)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00


In [6]:
import numpy as np

In [7]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
np.array([1,2,3,4,5]) + 10

array([11, 12, 13, 14, 15])

In [9]:
[1,2,3,4,5] +[10]

[1, 2, 3, 4, 5, 10]

In [10]:
np.array([[1,2,3,4],[6,7,8,9]])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [11]:
np.array([[1,2,3,4],[6,7,8,9]]).shape
#Define las filas y columnas del array

(2, 4)

In [14]:
np.array([[1,2,3,4],[6,7,8,9]])[0][2]

3

In [15]:
!pipenv install pandas

Installing pandas...
Adding pandas to Pipfile's [packages]...
✔ Installation Succeeded 
Installing dependencies from Pipfile.lock (be70db)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00


In [16]:
import pandas as pd

In [21]:
sr = pd.Series([10,9,8,7,6])
sr

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [19]:
sr.values

array([10,  9,  8,  7,  6])

In [20]:
sr.index

RangeIndex(start=0, stop=5, step=1)

In [22]:
sr.shape

(5,)

In [24]:
sr = pd.Series([10,9,8,7,6], index = ['a', 'b', 'c', 'd', 'e'])
sr

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [25]:
sr['c']

8

In [26]:
sr[['c', 'a']]

c     8
a    10
dtype: int64

In [28]:
sr['b': 'e']

b    9
c    8
d    7
e    6
dtype: int64

In [29]:
dict_data = {'CO': 100, 'MX': 200, 'AR': 300}
dict_data

{'CO': 100, 'MX': 200, 'AR': 300}

In [30]:
dict_data.keys()

dict_keys(['CO', 'MX', 'AR'])

In [31]:
dict_data['MX']

200

In [32]:
pd.Series(dict_data)

CO    100
MX    200
AR    300
dtype: int64

In [33]:
pd.Series(dict_data, index=['CO', 'MX', 'PE'])

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [34]:
#Un objeto nulo
np.nan

nan

In [35]:
np.nan + 10

nan

In [36]:
sr = pd.Series(dict_data, index=['CO', 'MX', 'PE'])
sr

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [37]:
sr.isnull()

CO    False
MX    False
PE     True
dtype: bool

In [38]:
type(sr.isnull())

pandas.core.series.Series