In [2]:
print('Hello world')

Hello world


In [3]:
lista = [1, 2, 3, 4, 5]

In [5]:
!pipenv install numpy

Installing numpy...
Adding numpy to Pipfile's [packages]...
✔ Installation Succeeded 
Installing dependencies from Pipfile.lock (be70db)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00


In [6]:
import numpy as np

In [7]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
np.array([1,2,3,4,5]) + 10

array([11, 12, 13, 14, 15])

In [9]:
[1,2,3,4,5] +[10]

[1, 2, 3, 4, 5, 10]

In [10]:
np.array([[1,2,3,4],[6,7,8,9]])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [11]:
np.array([[1,2,3,4],[6,7,8,9]]).shape
#Define las filas y columnas del array

(2, 4)

In [14]:
np.array([[1,2,3,4],[6,7,8,9]])[0][2]

3

In [ ]:
!pipenv install pandas

Installing pandas...
Adding pandas to Pipfile's [packages]...
✔ Installation Succeeded 
Installing dependencies from Pipfile.lock (be70db)...
